### ISSUE TITLE
Feature: User can search for cards by name, set, or rarity - 1

### ISSUE THREAD

**Issue by KevinUnkle** [KevinUnkle/Pokemon-Price#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Kevin Unkle - AJAX Project](https://github.com/KevinUnkle/ajax-project/assets/130183756/f8ef3324-5006-4ce4-9128-d970e80f1e13)
![Kevin Unkle - AJAX Project Mobile](https://github.com/KevinUnkle/ajax-project/assets/130183756/7fd4aa61-6575-4512-ac2d-965932510c97)

## ✅ Task List
- [x] - retrieve specific "base" id set to display upon page/app load
- [x] - 'GET', 'https://api.pokemontcg.io/v2/cards' with URL query 
          paramter (?) to get specific sets
- [x] - save each set in a variable with specified names
     - [x]  set id: 'base1' - Original 1999 series
     - [x]  set id: 'ex1' - EX series
     - [x]  set id: 'dp1' - Diamond and Pearl series
     - [x]  set id: 'bw1' - Black and White series
     - [x]  set id: 'xy1' - XY series
     - [x]  set id: 'sm1' - Sun and Moon series
     - [x]  set id: 'swsh1' - Sword and Shield series
     - [x]  set id: 'sv1' - Scarlet and Violet series
- [x] - retreive card set whose id starts with "base" to display on 
         page/app load
- [x] - Save filtered data into a new "cards" variable in data.js file
- [x] - create a div.row and div.column element to house the cards will be displayed on homepage
- [x] - create div's of equal size to house each individual card
- [x] - create a render entry function that populates "card" div information (remember the dom tree)
- [x] - loop through the "cards" array in data.js, save it in a variable, and call render entry function - save this in a variable as well
- [x] - append variable in previous step to the dom
- [x] - create the input search bar
     - [x] - add event listener for text input on search bar
     - [x] - confirm functionality that proper card(s) is/are retrieved from search
- [x] - create the filter bar
     - [x] - create filtering option
     - [x] set
- [x] add 'onclick' event listener to filter bar and save it to data.filter
     - [x] - confirm no bugs in filter process

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
